### ISSUE TITLE
Package missing from nuget?

### ISSUE THREAD

**Issue by sebastian** [CSBiology/FSharp.Stats#27]
### Description

[The documentation](https://csbiology.github.io/FSharp.Stats/index.html) specifies that the package is available on Nuget – but currently it doesn't seem to be.
Accessing [the provided Nuget link](https://www.nuget.org/packages/FSharp.Stats), one get's a 404 – not found.

### Repro steps

1. Visit the Nuget link: https://www.nuget.org/packages/FSharp.Stats
2. Realize package is missing

Alternatively:

1. Visit nuget.org
2. Search for `FSharp.Stats`
2. No results are returned: https://www.nuget.org/packages?q=FSharp.Stats

Thanks!

**Comment by kMutagene** [comment]
Hi @sebastian,
You are indeed correct, this is an artifact in our incomplete documentation for this project due to autogeneration of the pages. There is no package on nuget currently. However, we provide alpha packages on the [nuget branch](https://github.com/CSBiology/FSharp.Stats/tree/nuget). 
If you are using paket to manage your dependencies, you can add the package by adding the following lines to your paket.dependencies file:
`git https://github.com/CSBiology/FSharp.Stats.git nuget Packages: /`
`nuget FSharp.Stats`
I dont know how to use git as a source for the nuget package manager itself though, so if you dont use paket i am afraid that the only way i know of would then be a manual download from the repository.

**Comment by sebastian** [comment]
Thank you @kMutagene, appreciate you taking the time to answer!
I am in fact using `paket` so your proposed solution works well for me. Thanks!
